### ISSUE TITLE
用户注册后返回401

### ISSUE THREAD

**Issue by zaijianbch** [phith0n/mooder#11]
本地，源代码搭建的环境。
审核员生成邀请码，用户注册时返回错误<Response [401]>。
审核员界面已经能看到该用户，未启用，点击启用后弹出一个新的about:blank空页面。
无法启用该用户。
注册邮箱是乱填的test@test.com。
发送邮件未配置。

**Comment by phith0n** [comment]
用户注册后必须进行邮件验证。
所以发件邮箱必须配置。
另外，不支持古老的浏览器，请使用chrome或firefox。

**Comment by zaijianbch** [comment]
多谢p神了，我明天试试。
