### ISSUE TITLE
CentOS 6.6 python3.5.2安装python依赖django-pure-pagination时出错

### ISSUE THREAD

**Issue by leixyou** [phith0n/mooder#12]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ktf3be8v/django-pure-pagination/setup.py", line 5, in <module>
        README = readme.read()
      File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 672: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ktf3be8v/django-pure-pagination/

**Comment by phith0n** [comment]
https://github.com/jamespacileo/django-pure-pagination/issues/40

**Comment by phith0n** [comment]
可以试试直接从git安装：

```
pip install https://github.com/Burakhan/django-pure-pagination/archive/master.zip
```

**Comment by leixyou** [comment]
多谢大表哥！！搞好了
