### ISSUE TITLE
演示站点挂了

### ISSUE THREAD

**Issue by pierre94** [phith0n/mooder#19]

**Comment by deamwork** [comment]
Demo站点挂在DaoCloud下的……不知道p犇打算啥时候恢复一下，不过和文档里提到的是差不多的，具体内容可以自己部署一个试试看，毕竟是docker-compose出来的，一键部署很方便

**Comment by cxgreat2014** [comment]
> 演示站点不对外开放。

**Comment by phith0n** [comment]
本来是把演示站点放daocloud下，结果后来daocloud转型了，只能做短期的测试站点，所以就演示不了了。
