### ISSUE TITLE
ConnectionResetError at /register/

### ISSUE THREAD

**Issue by lucifer-0** [phith0n/mooder#24]
[Errno 104] Connection reset by peer
Request Method:	POST
Request URL:	http://1ocalhost:8000/register/ 
Django Version:	1.11.3 
Exception Type:	ConnectionResetError 
Exception Value:	 [Errno 104] Connection reset by peer Exception Location:	/usr/local/python/lib/python3.5/ssl.py in do_handshake, line 633 Python Executable:	/usr/local/python/bin/python3 Python Version:3.5.2 

按照文档上docker-compose up -d 运行，注册时就出现这个，是配置有问题还是？

**Comment by deamwork** [comment]
连接被RST了，可以试试连接到Container里面检查一下，或者检查一下证书链问题
如果能提供更多debug日志应该可以方便定位问题

**Comment by hanggegege** [comment]
从源码安装没问题
