### ISSUE TITLE
注册后发送的验证链接无法验证

### ISSUE THREAD

**Issue by lzy112314** [phith0n/mooder#25]
注册后验证的链接是example.com/activate/xxxxxx
不是我的服务器地址，无法验证，大神帮忙看下怎么调整才可以，我是linux源码安装，debug模式

**Comment by phith0n** [comment]
如果是nginx反向代理，请设置proxy_host，将host代理为你的域名。访客用什么域名访问的注册页面，发送的链接就是什么域名。

**Comment by lzy112314** [comment]
好的，谢谢大神
