### ISSUE TITLE
container日志中报psql command not found

### ISSUE THREAD

**Issue by whoadmin** [phith0n/mooder#33]
.whiskey/action_hooks/deploy: line 7: psql: command not found

**Comment by Err0rZero** [comment]
同样遇到这个问题

**Comment by phith0n** [comment]
周末处理这个问题

**Comment by cxgreat2014** [comment]
我的解决方案是docker exec 进入web容器手动安装postgresql，之后问题解决

**Comment by phith0n** [comment]
fixed on #38
