### ISSUE TITLE
源码安装.env文件中的配置无效

### ISSUE THREAD

**Issue by cxgreat2014** [phith0n/mooder#5]
源码安装中settings_production.py获取设置的方式为os.environ.get('config')，无法获取到.env文件内的配置

**Comment by phith0n** [comment]
这个文件是给docker-compose用的。

**Comment by cxgreat2014** [comment]
那源码安装该怎么配置呢？修改settings_production.py？。。。文档得说明一下

**Comment by phith0n** [comment]
好的，今晚修改文档

**Comment by cxgreat2014** [comment]
Thanks~:)
