### ISSUE TITLE
docker-compose up -d出错解决方案

### ISSUE THREAD

**Issue by cxgreat2014** [phith0n/mooder#7]
hook@ubuntu:~/mooder$ docker-compose up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
hook@ubuntu:~/mooder$
出现以上错误的解决方案：使用sudo

**Comment by Manasseh-Zhou** [comment]
请问您的docker 在运行么？
尝试运行一下`docker info`

**Comment by cxgreat2014** [comment]
docker的确在运行，执行docker-compose up -d出错，执行sudo docker-compose up -d成功编译

**Comment by phith0n** [comment]
确实是需要sudo的，如果你的docker是以管理员运行的，否则不需要。

**Comment by cxgreat2014** [comment]
文档可以加一句～:smile
